name: Lint and Format

on:
  push:
    branches:
      - main
  pull_request:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install npm dependencies (bun)
        run: bun install

      - name: Lint and Format
        run: bun lint && bun format
